# general settings
name: LKFN_x4
model_type: SRModel
scale: 4
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DL2K
    type: PairedImageDataset
    dataroot_gt: /media/cjd/66C880E6C880B5B9/SRdataset/DL2K/HR_sub.lmdb
    dataroot_lq: /media/cjd/66C880E6C880B5B9/SRdataset/DL2K/X4_sub.lmdb

    io_backend:
      # type: disk
      # (for lmdb)
      type: lmdb

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 6
    batch_size_per_gpu: 64
    dataset_enlarge_ratio: 100
    prefetch_mode: cuda
    pin_memory: true

#  val_1:
#    name: Set5
#    type: PairedImageDataset
#    dataroot_gt: /home/cjd/SRdataset/benchmark/Set5/HR
#    dataroot_lq: /home/cjd/SRdataset/benchmark/Set5/LR_bicubic/X4
#    filename_tmpl: '{}x4'
#    io_backend:
#      type: disk

  val_2:
    name: Set14
    type: PairedImageDataset
    dataroot_gt: /home/cjd/SRdataset/benchmark/Set14/HR
    dataroot_lq: /home/cjd/SRdataset/benchmark/Set14/LR_bicubic/X4
    filename_tmpl: '{}x4'
    io_backend:
      type: disk

  # val_3:
  #   name: Urban100
  #   type: PairedImageDataset
  #   dataroot_gt: datasets/Urban100/GTmod4
  #   dataroot_lq: datasets/Urban100/LRbicx4
  #   io_backend:
  #     type: disk

# network structures
network_g:
  type: LKFN
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 56
  num_atten: 56
  num_block: 8
  upscale: 4
  num_in: 4
  upsampler: pixelshuffledirect

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
#     type: Adam
#     lr: !!float 5e-3
#     weight_decay: 0
#     betas: [0.9, 0.999]

    type: Adan
    lr: !!float 5e-3
    betas: [0.98, 0.92, 0.99]
    weight_decay: 0
    foreach: true

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [ 1000000 ]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 1000000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~
    entity: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500 backend: nccl
  port: 29500